# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Translator(object):
    def setupUi(self, Translator):
        Translator.setObjectName("Translator")
        Translator.setFixedSize(700, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Translator.sizePolicy().hasHeightForWidth())
        Translator.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        Translator.setFont(font)
        Translator.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Translator.setMouseTracking(False)
        Translator.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Translator.setWindowIcon(icon)
        Translator.setWindowOpacity(0.88)
        Translator.setLayoutDirection(QtCore.Qt.LeftToRight)
        Translator.setAutoFillBackground(False)
        Translator.setStyleSheet("color: rgb(6, 72, 255);")
        Translator.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gridLayoutWidget = QtWidgets.QWidget(Translator)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 69, 681, 421))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.JaEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JaEdit.sizePolicy().hasHeightForWidth())
        self.JaEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(13)
        self.JaEdit.setFont(font)
        self.JaEdit.setMouseTracking(False)
        self.JaEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.JaEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.JaEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.JaEdit.setFrame(False)
        self.JaEdit.setReadOnly(True)
        self.JaEdit.setClearButtonEnabled(False)
        self.JaEdit.setObjectName("JaEdit")
        self.gridLayout.addWidget(self.JaEdit, 0, 1, 1, 1)
        self.FrenchLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FrenchLabel.sizePolicy().hasHeightForWidth())
        self.FrenchLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        self.FrenchLabel.setFont(font)
        self.FrenchLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.FrenchLabel.setObjectName("FrenchLabel")
        self.gridLayout.addWidget(self.FrenchLabel, 4, 0, 1, 1)
        self.EnEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnEdit.sizePolicy().hasHeightForWidth())
        self.EnEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(13)
        self.EnEdit.setFont(font)
        self.EnEdit.setMouseTracking(False)
        self.EnEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.EnEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.EnEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.EnEdit.setFrame(False)
        self.EnEdit.setReadOnly(True)
        self.EnEdit.setClearButtonEnabled(False)
        self.EnEdit.setObjectName("EnEdit")
        self.gridLayout.addWidget(self.EnEdit, 1, 1, 1, 1)
        self.RussianLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RussianLabel.sizePolicy().hasHeightForWidth())
        self.RussianLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        self.RussianLabel.setFont(font)
        self.RussianLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.RussianLabel.setObjectName("RussianLabel")
        self.gridLayout.addWidget(self.RussianLabel, 2, 0, 1, 1)
        self.RuEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RuEdit.sizePolicy().hasHeightForWidth())
        self.RuEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(13)
        self.RuEdit.setFont(font)
        self.RuEdit.setMouseTracking(False)
        self.RuEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.RuEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.RuEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.RuEdit.setFrame(False)
        self.RuEdit.setReadOnly(True)
        self.RuEdit.setClearButtonEnabled(False)
        self.RuEdit.setObjectName("RuEdit")
        self.gridLayout.addWidget(self.RuEdit, 2, 1, 1, 1)
        self.EsEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EsEdit.sizePolicy().hasHeightForWidth())
        self.EsEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(13)
        self.EsEdit.setFont(font)
        self.EsEdit.setMouseTracking(False)
        self.EsEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.EsEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.EsEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.EsEdit.setText("")
        self.EsEdit.setFrame(False)
        self.EsEdit.setReadOnly(True)
        self.EsEdit.setClearButtonEnabled(False)
        self.EsEdit.setObjectName("EsEdit")
        self.gridLayout.addWidget(self.EsEdit, 5, 1, 1, 1)
        self.CnEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CnEdit.sizePolicy().hasHeightForWidth())
        self.CnEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(13)
        self.CnEdit.setFont(font)
        self.CnEdit.setMouseTracking(False)
        self.CnEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.CnEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.CnEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.CnEdit.setFrame(False)
        self.CnEdit.setReadOnly(True)
        self.CnEdit.setClearButtonEnabled(False)
        self.CnEdit.setObjectName("CnEdit")
        self.gridLayout.addWidget(self.CnEdit, 3, 1, 1, 1)
        self.FrEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FrEdit.sizePolicy().hasHeightForWidth())
        self.FrEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(13)
        self.FrEdit.setFont(font)
        self.FrEdit.setMouseTracking(False)
        self.FrEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.FrEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.FrEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.FrEdit.setFrame(False)
        self.FrEdit.setReadOnly(True)
        self.FrEdit.setClearButtonEnabled(False)
        self.FrEdit.setObjectName("FrEdit")
        self.gridLayout.addWidget(self.FrEdit, 4, 1, 1, 1)
        self.ChineseLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChineseLabel.sizePolicy().hasHeightForWidth())
        self.ChineseLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        self.ChineseLabel.setFont(font)
        self.ChineseLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ChineseLabel.setObjectName("ChineseLabel")
        self.gridLayout.addWidget(self.ChineseLabel, 3, 0, 1, 1)
        self.JapaneseLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JapaneseLabel.sizePolicy().hasHeightForWidth())
        self.JapaneseLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        self.JapaneseLabel.setFont(font)
        self.JapaneseLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.JapaneseLabel.setTextFormat(QtCore.Qt.AutoText)
        self.JapaneseLabel.setObjectName("JapaneseLabel")
        self.gridLayout.addWidget(self.JapaneseLabel, 0, 0, 1, 1)
        self.EnglishLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnglishLabel.sizePolicy().hasHeightForWidth())
        self.EnglishLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        self.EnglishLabel.setFont(font)
        self.EnglishLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.EnglishLabel.setObjectName("EnglishLabel")
        self.gridLayout.addWidget(self.EnglishLabel, 1, 0, 1, 1)
        self.SpanishLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpanishLabel.sizePolicy().hasHeightForWidth())
        self.SpanishLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        self.SpanishLabel.setFont(font)
        self.SpanishLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.SpanishLabel.setObjectName("SpanishLabel")
        self.gridLayout.addWidget(self.SpanishLabel, 5, 0, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Translator)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 681, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setMouseTracking(False)
        self.textEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.textEdit.setMaxLength(500)
        self.textEdit.setFrame(True)
        self.textEdit.setDragEnabled(False)
        self.textEdit.setClearButtonEnabled(True)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_2.addWidget(self.textEdit)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)

        self.retranslateUi(Translator)
        QtCore.QMetaObject.connectSlotsByName(Translator)

    def retranslateUi(self, Translator):
        _translate = QtCore.QCoreApplication.translate
        Translator.setWindowTitle(_translate("Translator", "Translator"))
        self.FrenchLabel.setText(_translate("Translator", "French:"))
        self.RussianLabel.setText(_translate("Translator", "Russian:"))
        self.ChineseLabel.setText(_translate("Translator", "Chinese:"))
        self.JapaneseLabel.setText(_translate("Translator", "Japanese:"))
        self.EnglishLabel.setText(_translate("Translator", "English:"))
        self.SpanishLabel.setText(_translate("Translator", "Spanish:"))
        self.textEdit.setPlaceholderText(_translate("Translator", "Enter text (max 500 characters)."))
        self.pushButton.setText(_translate("Translator", "Translate"))
        self.pushButton.setShortcut(_translate("Translator", "Return"))
